### PR TITLE
FIX-#106: Change directories to be checked by linters

### LINKED ISSUE #106: Change directories to be checked by linters
We should change directories to be checked by linters because there might be some autogenerated files with specific formatting like in #105 or some files that require putting import of a module not at the top of a file.

### PR DESCRIPTION
**Pull request by YarShev**
Signed-off-by: Igoshev, Yaroslav <yaroslav.igoshev@intel.com>

## What do these changes do?

- [x] passes `flake8 unidist/`
- [x] passes `black unidist/`
- [x] signed commit with `git commit -s` 
- [x] Resolves #106  
- [x] tests passing
- [x] module layout described at `docs/developer/architecture.rst` is up-to-date

### CODE REVIEW

**Comment by prutskov** [comment]
Let's just add config files for [`black`](https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#configuration-via-a-file) and [`flake8`](https://flake8.pycqa.org/en/latest/user/configuration.html)(it's present already in our repo). The both of linters have `exclude` option which could be used for excluding auto-generated files from checks. It would be better than check only `unidist` folder, because we have other `.py` files outside it.

**Comment by YarShev** [comment]
We do not yet have specific config files for black and flake8 in our repo. We only have setup.cfg in which there are some configuration settings for flake8. Major part of our code is mostly located in unidist directory. I do not see a lot of sense to check autogenerated files because those contain not our code, we only add some specific parts of code for our needs.

**Comment by prutskov** [comment]
> We do not yet have specific config files for black and flake8 in our repo. We only have setup.cfg in which there are some configuration settings for flake8. Major part of our code is mostly located in unidist directory. I do not see a lot of sense to check autogenerated files because those contain not our code, we only add some specific parts of code for our needs.

As I mentioned above. I propose to:

1. **Add** config file for `black` (for `flake8` is already presented).
2. Add autogenerated python files to **exclusions** via `exclude` option for both linters.

I don't propose to check autogenerated files. But prefer to check all .py files (unidist/*, docs/*.py, setup.py and, possible, future .py files) excluding autogenerated. Excluding is the best solution in this case instead of leaving checks to `unidist` folder only.

**Comment by YarShev** [comment]
> Excluding is the best solution in this case instead of leaving checks for unidist folder only.

This is the same as if we specify a specific directory to be checked. I do not see a reason for checking everything (i.e. doing `.`).

**Comment by YarShev** [comment]
We want to check only our code not to bloat configs with exclude files so I suggest leaving as it is. If we see a real reason to check everything, we will add those config files, but I am not sure that happens.

**Comment by prutskov** [comment]
> > Excluding is the best solution in this case instead of leaving checks for unidist folder only.
> 
> This is the same as if we specify a specific directory to be checked. I do not see a reason for checking everything (i.e. doing `.`).

This is not true. In this case you should check `unidist/, docs/*.py, setup.py` at least instead of just `unidist` folder check. There are at least two reasons to have a set of exclusions instead of set of inclusions:

1. Exclusions set give a more control of linting process. If in the future we will add additional .py files in repo, we don't have to think about including them in linting checks.
2. It's much easier and useful for contributors to do `black .` instead of `black unidist/ docs/conf.py setup.py something_other.py`.


> We want to check only our code not to bloat configs with exclude files so I suggest leaving as it is. If we see a real reason to check everything, we will add those config files, but I am not sure that happens.

We already checks everything and I don't see a real reason to stop doing this just because of we will have 2 files for exclusions after #106.

**Comment by YarShev** [comment]
> We already checks everything

Why do we do so? Did we take it over from Modin at some point? We check only specific directories in Modin now.

> we will have 2 files for exclusions after #105.

Whenever we add autogenerated files, which should not be checked by linters, we will have to add those files to config files that makes it difficult development and bloat the configs.

**Comment by prutskov** [comment]
> Why do we do so? Did we take it over from Modin at some point? We check only specific directories in Modin now.

We do so, because linting should be applied to the entire project. It's strange to have formatting rules only for a part of codebase without specific reasons like autogenerated files e.g. (Modin is example of this approach). I don't think that we should copy this behavior from Modin as we don't have specific reasons.
 
> Whenever we add autogenerated files, which should not be checked by linters, we will have to add those files to config files that makes it difficult development and bloat the configs.

I don't see a problem here because adding of autogenerated files to the repo is enough rare. If this is often event, need to think about approach of generating this files only by need without placing in the repo.

We will add more often additional .py files not in `unidist/` folder (`benchmarks`, `scripts` e.g.) than autogenerated files.

In your approach it will be more development difficulties and bloating the configs (`black unidist/ docs/ setup.py scripts/ benchs/ something_else/`). Moreover, additional responsibility for developers to include new .py files into all checks/contributing guide.

**Comment by YarShev** [comment]
> In your approach it will be more development difficulties and bloating the configs (`black unidist/ docs/ setup.py scripts/ benchs/ something_else/`). Moreover, additional responsibility for developers to include new .py files into all checks/contributing guide.

I do not understand why there will be more development difficulties and bloating the configs? The user only needs to add a directory to be checked to black/flake8, that's it. He doesn't need to know syntax of the configuration files and all the options which he wants to apply. Adding an additional directory to be checked to docs is not a development difficulty.

**Comment by prutskov** [comment]
> I do not understand why there will be more development difficulties and bloating the configs? The user only needs to add a directory to be checked to black/flake8, that's it. He doesn't need to know syntax of the configuration files and all the options which he wants to apply. Adding an additional directory to be checked to docs is not a development difficulty.

But user no needs to do anything in case adding of directories/modules/files if the approach I proposed is used. He will interact with configs of flake8/black ONLY in case adding an autogenerated files (and those configs already will have examples with files like `unidist/_version.py` e.g.). This, as I mentioned above, is a rarely situation. And I don't see the point of need to know syntax of config files in this case (just example usage which will already in the repo).

In your case user will add directories to be checked in several places of our codebase including CI/RST in different files and can miss to do this.

**Comment by YarShev** [comment]
Discussed offline and decided to check all files and use exclude files as an appropriate option for now. So, closing the PR.

**Pull request closed without merging**
