### PR TITLE
FIX-#104: Add testing py3.9 in CI

### LINKED ISSUE #104: Add testing on python 3.9 to CI
After upgrading min version python >= 3.8 there were some problems with running MPI backend on python 3.9. We should investigate that and fix if possible.

```
Run python unidist/cli -m pytest unidist/test/
mpiexec: Error: unknown option "-o"
Type 'mpiexec --help' for usage.
Traceback (most recent call last):
  File "/usr/share/miniconda/envs/unidist/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/share/miniconda/envs/unidist/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/runner/work/unidist/unidist/unidist/cli/__main__.py", line 122, in <module>
    main()
  File "/home/runner/work/unidist/unidist/unidist/cli/__main__.py", line 118, in main
    runner.run()
  File "/home/runner/work/unidist/unidist/unidist/cli/base/runner.py", line 57, in run
    subprocess.run(command, check=True)
  File "/usr/share/miniconda/envs/unidist/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['mpiexec', '-hosts', '10.1.1.42:1,10.1.1.42:1,10.1.1.42:2,', '-n', '1', 'python', '-m', 'pytest', 'unidist/test/', ':', '-n', '1', '-wdir', '/tmp', 'python', '/home/runner/work/unidist/unidist/unidist/core/backends/mpi/core/monitor.py', ':', '-n', '2', '-wdir', '/tmp', 'python', '/home/runner/work/unidist/unidist/unidist/core/backends/mpi/core/worker.py']' returned non-zero exit status 1.
Error: Process completed with exit code 1.
```

### PR DESCRIPTION
**Pull request by prutskov**
Signed-off-by: Alexey Prutskov <alexey.prutskov@intel.com>

## What do these changes do?

- [x] passes `flake8 .`
- [x] passes `black .`
- [x] signed commit with `git commit -s` 
- [x] Resolves #104 
- [x] tests added and passing
- [ ] module layout described at `docs/developer/architecture.rst` is up-to-date

### CODE REVIEW

**Comment by prutskov** [comment]
PR is blocked because It's need cluster-check. I will notify @no-ponomarev, @YarShev

**Comment by aregm** [comment]
I think you should add 3.10 too.

**Comment by prutskov** [comment]
> I think you should add 3.10 too.

This can't be done for Ray backend, because it doesn't support py310. Does partial testing make sense without Ray for 3.10?

**Comment by YarShev** [comment]
I think we can do that as part of a separate issue.

**Comment by prutskov** [comment]
The changes were tested on cluster. All work as expected. @YarShev, @no-ponomarev PR is unblocked.

> I think we can do that as part of a separate issue.

Agree, let's do by this way

**Review by YarShev — APPROVED** [review]

**Comment by YarShev** [comment]
@prutskov, thanks for testing in different environments.

**Pull request merged**
